server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: ${DBMS_URL:jdbc:mysql://localhost:3306/movie}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
